# #################################
# Parameters of the final model
#
# Authors:
#  * Heitor Guimarães 2022
#  * Miguel Arjona    2022
#  * Wesley Beccaro   2022
# #################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
exp_name: td_fcn_5layers_10epochs_100h
data_folder: ../dataset
output_folder: !ref ../logs/<exp_name>
model_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
audio_result: !ref <output_folder>/audio_results
npy_result: !ref <output_folder>/npy_results

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json

train_folder:
  - !ref <data_folder>/L3DAS22_Task1_train100
valid_folder: !ref <data_folder>/L3DAS22_Task1_dev
test_folder: !ref <data_folder>/L3DAS22_Task1_test_no_labels

# logs with training statistics
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Training Parameters
train_sampling: True
max_train_sample_size: 80000    # Maximum number of samples to use during train
number_of_epochs: 10
batch_size: 2

train_dataloader_options:
    batch_size: !ref <batch_size>

valid_dataloader_options:
    batch_size: !ref <batch_size>

test_dataloader_options:
    batch_size: 1

# Optimizer and Scheduler parameters
lr: 0.0001
gradient_accumulation: 2
clip_grad_norm: 10
loss_upper_lim: 100
threshold_byloss: True
threshold: -100

# # Model construction
model: !new:denoiser.models.TDFCN1D
    num_channels: 4
    rep_channels: 80
    kernel_size: 55

loss: !new:denoiser.losses.PerceptualLoss
    PRETRAINED_MODEL_PATH: '../pretrained/'
    model_architecture: 'wav2vec2'
    distance_metric: 'l2'

modules:
    model: !ref <model>
    loss: !ref <loss>

# # Optimizer parameters
opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 2
    dont_halve_until_epoch: 15

# Save state of the training process
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <model_folder>
    recoverables:
        model: !ref <model>
        optimizer: !ref <opt_class>
        counter: !ref <epoch_counter>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>