# #################################
# Parameters of the final model
#
# Authors:
#  * Heitor Guimarães 2021
#  * Miguel Arjona    2021
#  * Wesley Beccaro   2021
# #################################

seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
exp_name: time_domain_250epochs_5layers_pfpl_conformer_100h
data_folder: ../dataset
output_folder: !ref ../logs/<exp_name>
model_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
audio_result: !ref <output_folder>/audio_results
npy_result: !ref <output_folder>/npy_results

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
train_folder:
  - !ref <data_folder>/L3DAS22_Task1_train100
valid_folder: !ref <data_folder>/L3DAS22_Task1_dev
test_folder: !ref <data_folder>/L3DAS22_Task1_dev

# logs with training statistics
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Training Parameters
train_sampling: True
max_train_sample_size: 48000    # Maximum number of samples to use during train
number_of_epochs: 250
batch_size: 4

dataloader_options:
    batch_size: !ref <batch_size>

test_dataloader_options:
    batch_size: 1

# Optimizer and Scheduler parameters
gradient_accumulation: 2
lr: 0.0005

# STFT
sample_rate: 16000
win_length: 32
hop_length: 16
n_fft: 512
window_fn: !name:torch.hamming_window

compute_stft: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <sample_rate>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>
    n_fft: !ref <n_fft>
    window_fn: !ref <window_fn>

compute_istft: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <sample_rate>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>
    window_fn: !ref <window_fn>

# # Model construction
depth: 5
model: !new:denoiser.models.HybridDenoiser
    depth: !ref <depth>
    in_ch: 2
    base_ch: 48
    T_ks: 8
    T_stride: 4
    resampling: True
    compute_stft: !ref <compute_stft>
    compute_istft: !ref <compute_istft>

loss: !new:denoiser.losses.PerceptualLoss
    PRETRAINED_MODEL_PATH: '../pretrained/'

modules:
    model: !ref <model>
    loss: !ref <loss>

# # Optimizer parameters
opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

# Save state of the training process
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <model_folder>
    recoverables:
        model: !ref <model>
        optimizer: !ref <opt_class>
        counter: !ref <epoch_counter>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>